### ISSUE TITLE
Deploy In Heroku 

### ISSUE THREAD

**Issue by NinjaAtWork** [imohitmayank/jaal#29]
Hi
I can run the app in local easily 
But after following the heroku guide in official dash site at  [Link](https://dash.plotly.com/deployment) 
It says that server address is wrong which seems related to `plot()` `server` and `port` parameters 
How can i setup Jaal to run in heroku ?
Thanks for Great repo

**Comment by imohitmayank** [comment]
Hi @NinjaAtWork, can you please share the exact code used for deployment and the error message you got? It could help with debugging. Thnx!

**Comment by NinjaAtWork** [comment]
app.py:
```
from sys import path
import numpy as np
import pandas as pd
from jaal import Jaal
from jaal.datasets import load_got
from pathlib import Path


node_df = pd.read_csv(Path.cwd() / "csv" / "scrap.csv")
edge_df = pd.read_csv(Path.cwd() / "csv" / "distance.csv")
# edge_df, node_df = load_got()
edge_df.loc[:, 'label'] = (np.round(edge_df.loc[:, 'distance'], 2)).astype(str)

# init Jaal and run server
# Jaal(edge_df, node_df).plot()

# init Jaal and run server
if __name__ == '__main__':
    Jaal(edge_df, node_df).plot(vis_opts={'height': '800px',  # change height
                                          # turn on-off the hover
                                          'interaction': {'hover': True},
                                          'physics': {'stabilization': {'iterations': 100}}})  # define the convergence iteration of network
```

heroku logs --tail:
(i added` server = app.server` right after the `app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])` but no luck)
(also encapsulated the Jall() in if __name__==__main__ still problem exist)
```
2021-08-28T15:43:12.515559+00:00 app[web.1]: [2021-08-28 15:43:12 +0000] [4] [INFO] Using worker: sync
2021-08-28T15:43:12.518656+00:00 app[web.1]: [2021-08-28 15:43:12 +0000] [7] [INFO] Booting worker with pid: 7
2021-08-28T15:43:12.560991+00:00 app[web.1]: [2021-08-28 15:43:12 +0000] [15] [INFO] Booting worker with pid: 15
2021-08-28T15:43:12.997085+00:00 heroku[web.1]: State changed from starting to up
2021-08-28T15:43:16.159939+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-08-28T15:43:16.159987+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-08-28T15:43:16.160062+00:00 app[web.1]: [2021-08-28 15:43:16 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-08-28T15:43:16.160138+00:00 app[web.1]: [2021-08-28 15:43:16 +0000] [15] [INFO] Worker exiting (pid: 15)
2021-08-28T15:43:16.265059+00:00 app[web.1]: Traceback (most recent call last):
2021-08-28T15:43:16.265066+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
2021-08-28T15:43:16.265312+00:00 app[web.1]: self.sleep()
2021-08-28T15:43:16.265314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep       
2021-08-28T15:43:16.265435+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2021-08-28T15:43:16.265437+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld 
2021-08-28T15:43:16.265519+00:00 app[web.1]: self.reap_workers()
2021-08-28T15:43:16.265527+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2021-08-28T15:43:16.265653+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2021-08-28T15:43:16.265691+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2021-08-28T15:43:16.265699+00:00 app[web.1]: 
2021-08-28T15:43:16.265700+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-08-28T15:43:16.265700+00:00 app[web.1]: 
2021-08-28T15:43:16.265701+00:00 app[web.1]: Traceback (most recent call last):
2021-08-28T15:43:16.265709+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2021-08-28T15:43:16.265764+00:00 app[web.1]: sys.exit(run())
2021-08-28T15:43:16.265772+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run      
2021-08-28T15:43:16.265834+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2021-08-28T15:43:16.265835+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run        
2021-08-28T15:43:16.265921+00:00 app[web.1]: super().run()
2021-08-28T15:43:16.265923+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2021-08-28T15:43:16.265980+00:00 app[web.1]: Arbiter(self).run()
2021-08-28T15:43:16.265989+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2021-08-28T15:43:16.266064+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2021-08-28T15:43:16.266072+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2021-08-28T15:43:16.266167+00:00 app[web.1]: self.stop()
2021-08-28T15:43:16.266175+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 382, in stop
2021-08-28T15:43:16.266280+00:00 app[web.1]: sock.close_sockets(self.LISTENERS, unlink)
2021-08-28T15:43:16.266282+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/sock.py", line 210, in close_sockets
2021-08-28T15:43:16.266358+00:00 app[web.1]: sock.close()
2021-08-28T15:43:16.266367+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/sock.py", line 67, in close
2021-08-28T15:43:16.266422+00:00 app[web.1]: self.sock.close()
2021-08-28T15:43:16.266431+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/socket.py", line 501, in close
2021-08-28T15:43:16.266579+00:00 app[web.1]: self._real_close()
2021-08-28T15:43:16.266588+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/socket.py", line 495, in _real_close
2021-08-28T15:43:16.266731+00:00 app[web.1]: _ss.close(self)
2021-08-28T15:43:16.266732+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2021-08-28T15:43:16.266810+00:00 app[web.1]: self.reap_workers()
2021-08-28T15:43:16.266819+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2021-08-28T15:43:16.266937+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2021-08-28T15:43:16.266968+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2021-08-28T15:43:16.335937+00:00 heroku[web.1]: Process exited with status 1
2021-08-28T15:43:16.476413+00:00 heroku[web.1]: State changed from up to crashed
2021-08-28T15:43:23.000000+00:00 app[api]: Build succeeded
2021-08-28T15:43:46.947035+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=marine-dash.herokuapp.com request_id=60899451-e7b5-4c43-80fb-14fc5d43ddb6 fwd="89.219.96.183" dyno= connect= service= status=503 bytes= protocol=https
2021-08-28T15:55:07.634497+00:00 heroku[web.1]: State changed from crashed to starting
2021-08-28T15:55:16.316464+00:00 heroku[web.1]: Starting process with command `gunicorn app:server`
2021-08-28T15:55:18.379726+00:00 app[web.1]: [2021-08-28 15:55:18 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-08-28T15:55:18.381152+00:00 app[web.1]: [2021-08-28 15:55:18 +0000] [4] [INFO] Listening at: http://0.0.0.0:35092 (4)
2021-08-28T15:55:18.381198+00:00 app[web.1]: [2021-08-28 15:55:18 +0000] [4] [INFO] Using worker: sync
2021-08-28T15:55:18.384131+00:00 app[web.1]: [2021-08-28 15:55:18 +0000] [7] [INFO] Booting worker with pid: 7
2021-08-28T15:55:18.442087+00:00 app[web.1]: [2021-08-28 15:55:18 +0000] [15] [INFO] Booting worker with pid: 15
2021-08-28T15:55:19.975730+00:00 heroku[web.1]: State changed from starting to up
2021-08-28T15:55:22.850303+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-08-28T15:55:22.850473+00:00 app[web.1]: [2021-08-28 15:55:22 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-08-28T15:55:22.854773+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-08-28T15:55:22.854972+00:00 app[web.1]: [2021-08-28 15:55:22 +0000] [15] [INFO] Worker exiting (pid: 15)
2021-08-28T15:55:22.965362+00:00 app[web.1]: Traceback (most recent call last):
2021-08-28T15:55:22.965369+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
2021-08-28T15:55:22.965685+00:00 app[web.1]: self.sleep()
2021-08-28T15:55:22.965686+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
2021-08-28T15:55:22.965878+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2021-08-28T15:55:22.965887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2021-08-28T15:55:22.966023+00:00 app[web.1]: self.reap_workers()
2021-08-28T15:55:22.966031+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2021-08-28T15:55:22.966234+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2021-08-28T15:55:22.966293+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2021-08-28T15:55:22.966296+00:00 app[web.1]:
2021-08-28T15:55:22.966296+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-08-28T15:55:22.966296+00:00 app[web.1]:
2021-08-28T15:55:22.966305+00:00 app[web.1]: Traceback (most recent call last):
2021-08-28T15:55:22.966314+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2021-08-28T15:55:22.966394+00:00 app[web.1]: sys.exit(run())
2021-08-28T15:55:22.966395+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2021-08-28T15:55:22.966466+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2021-08-28T15:55:22.966478+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
2021-08-28T15:55:22.966591+00:00 app[web.1]: super().run()
2021-08-28T15:55:22.966601+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2021-08-28T15:55:22.966676+00:00 app[web.1]: Arbiter(self).run()
2021-08-28T15:55:22.966685+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2021-08-28T15:55:22.966792+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2021-08-28T15:55:22.966794+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2021-08-28T15:55:22.966958+00:00 app[web.1]: self.stop()
2021-08-28T15:55:22.966966+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
2021-08-28T15:55:22.967105+00:00 app[web.1]: time.sleep(0.1)
2021-08-28T15:55:22.967107+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2021-08-28T15:55:22.967189+00:00 app[web.1]: self.reap_workers()
2021-08-28T15:55:22.967197+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2021-08-28T15:55:22.967324+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2021-08-28T15:55:22.967345+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2021-08-28T15:55:23.044314+00:00 heroku[web.1]: Process exited with status 1
2021-08-28T15:55:23.121817+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by NinjaAtWork** [comment]
also i have a 
Procfile:
`web: gunicorn app:server `
the problem seems to return to the line:
`Failed to find attribute 'server' in 'app'.`
which seems i have to add below line to server side Jaal:
`server = app.server`
at end i dunno whats to do

**Comment by NinjaAtWork** [comment]
Have you ever tried jaal on server or heroku server?

**Comment by imohitmayank** [comment]
@NinjaAtWork so, I have not yet tried Jaal with any production level HTTP server. I think the issue is that the Jaal module call creates and then hosts the app on python based HTTP server, but if you want to use something like gunicorn, Jaal should just create the app and then return the app for hosting by gunicorn. Maybe we can have a separate function like `Jaal.create` that does everything `Jaal.plot` does, except hosting. It will return the app and you should then be able to host it. 
Will get back on this and thnx for sharing this issue! 👍

**Comment by imohitmayank** [comment]
hi @NinjaAtWork, FYI - pushed a new version (`Jaal v0.1.0`) that should help with this problem. See [this example in readme](https://github.com/imohitmayank/jaal#using-gunicorn) on how to use `gunicorn` with Jaal. Let me know in case of any issue.

**Comment by NinjaAtWork** [comment]
Hi
thanks for update but still cant run app in heroku server properly ,(it seems ` server =app.server` should be before this line `app.run_server()` in .plot() .)

this is part of debug:
```
2021-09-01T21:32:15.014095+00:00 heroku[web.1]: Starting process with command `gunicorn app:server`
2021-09-01T21:32:18.107354+00:00 app[web.1]: [2021-09-01 21:32:18 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-09-01T21:32:18.108896+00:00 app[web.1]: [2021-09-01 21:32:18 +0000] [4] [INFO] Listening at: http://0.0.0.0:33228 (4)
2021-09-01T21:32:18.108948+00:00 app[web.1]: [2021-09-01 21:32:18 +0000] [4] [INFO] Using worker: sync
2021-09-01T21:32:18.111977+00:00 app[web.1]: [2021-09-01 21:32:18 +0000] [7] [INFO] Booting worker with pid: 7
2021-09-01T21:32:18.149796+00:00 app[web.1]: [2021-09-01 21:32:18 +0000] [8] [INFO] Booting worker with pid: 8
2021-09-01T21:32:19.615163+00:00 heroku[web.1]: State changed from starting to up
2021-09-01T21:32:23.343674+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-09-01T21:32:23.343849+00:00 app[web.1]: [2021-09-01 21:32:23 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-09-01T21:32:23.344609+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-09-01T21:32:23.344754+00:00 app[web.1]: [2021-09-01 21:32:23 +0000] [8] [INFO] Worker exiting (pid: 8)
```
and it try a few times more which produce this again:

```
2021-09-01T21:32:24.165208+00:00 heroku[web.1]: State changed from crashed to starting
2021-09-01T21:32:29.000000+00:00 app[api]: Build succeeded
2021-09-01T21:32:31.642510+00:00 heroku[web.1]: Starting process with command `gunicorn app:server`
2021-09-01T21:32:34.264824+00:00 app[web.1]: [2021-09-01 21:32:34 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-09-01T21:32:34.267156+00:00 app[web.1]: [2021-09-01 21:32:34 +0000] [4] [INFO] Listening at: http://0.0.0.0:37883 (4)
2021-09-01T21:32:34.267238+00:00 app[web.1]: [2021-09-01 21:32:34 +0000] [4] [INFO] Using worker: sync
2021-09-01T21:32:34.270894+00:00 app[web.1]: [2021-09-01 21:32:34 +0000] [7] [INFO] Booting worker with pid: 7
2021-09-01T21:32:34.312536+00:00 app[web.1]: [2021-09-01 21:32:34 +0000] [8] [INFO] Booting worker with pid: 8
2021-09-01T21:32:34.930562+00:00 heroku[web.1]: State changed from starting to up
2021-09-01T21:32:38.535451+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-09-01T21:32:38.535629+00:00 app[web.1]: [2021-09-01 21:32:38 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-09-01T21:32:38.538491+00:00 app[web.1]: Failed to find attribute 'server' in 'app'.
2021-09-01T21:32:38.538687+00:00 app[web.1]: [2021-09-01 21:32:38 +0000] [8] [INFO] Worker exiting (pid: 8)
2021-09-01T21:32:38.676156+00:00 app[web.1]: [2021-09-01 21:32:38 +0000] [4] [WARNING] Worker with pid 8 was terminated due to signal 15
2021-09-01T21:32:38.771158+00:00 app[web.1]: [2021-09-01 21:32:38 +0000] [4] [INFO] Shutting down: Master
2021-09-01T21:32:38.771190+00:00 app[web.1]: [2021-09-01 21:32:38 +0000] [4] [INFO] Reason: App failed to load.
2021-09-01T21:32:38.829164+00:00 heroku[web.1]: Process exited with status 4
2021-09-01T21:32:38.999168+00:00 heroku[web.1]: State changed from up to crashed
```

may i ask you try this on a free account in heroku.com server .i am using this [link ](https://dash.plotly.com/deployment)to deploy jaal which work like a charm for dash apps.

thank you

**Comment by imohitmayank** [comment]
Did you try using `Jaal.create()` as suggested in the example I linked before? That way you can return the created app and extract the server that can be hosted like any other dash app. These are the lines from the example,
```python
app = Jaal(edge_df, node_df).create()
server = app.server
```
